<?php
/**
 * Shared bootstrap for every wizard step page (1-welcome.php … 8-confirmation.php).
 *
 * Provides:
 *   - Session start + token resolution + RenewalSession loading
 *   - $session  (RenewalSession)
 *   - $client   (clients row, for prefill)
 *   - Variables expected by header.php / progress-bar.php
 *
 * Behaviour:
 *   - No token / invalid token  → redirect to index.php (which shows error page)
 *   - Wrong state for this step → redirect to whichever step is appropriate
 *
 * Each step page must define BEFORE including this file:
 *     $PFM_STEP        = 1..8;           // current step number
 *     $PFM_STEP_TITLE  = 'Welcome';      // page <title> + card heading
 *     $PFM_REQUIRES    = 'draft';        // 'draft' | 'submitted' | 'paid' | 'any'
 */

declare(strict_types=1);

define('RNW_ROOT', dirname(__DIR__, 2));

require_once RNW_ROOT . '/config/config.php';
require_once RNW_ROOT . '/lib/RenewalSession.php';
require_once RNW_ROOT . '/lib/BuyerManager.php';
require_once RNW_ROOT . '/lib/DocumentUpload.php';
require_once RNW_ROOT . '/lib/StripeClient.php';

// ── Session setup (must match index.php / api_bootstrap.php) ────────
$pfmSessionDir = RNW_ROOT . '/storage/sessions';
if (is_dir($pfmSessionDir)) {
    session_save_path($pfmSessionDir);
}
if (session_status() === PHP_SESSION_NONE) {
    session_set_cookie_params([
        'lifetime' => 0,
        'path'     => '/renewal_v2/',
        'secure'   => isset($_SERVER['HTTPS']),
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_start();
}

// ── Token resolution ────────────────────────────────────────────────
$token = (string) ($_SESSION['renewal_token'] ?? $_GET['token'] ?? '');
if ($token === '') {
    header('Location: /renewal_v2/public/index.php');
    exit;
}

$session = RenewalSession::loadOrCreate($token);
if ($session === null) {
    unset($_SESSION['renewal_token']);
    header('Location: /renewal_v2/public/index.php');
    exit;
}
$_SESSION['renewal_token'] = $session->token;

// ── CSRF token (generated by api_bootstrap on first use — ensure it exists) ─
if (empty($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}

// ── State gating ────────────────────────────────────────────────────
$requires = $PFM_REQUIRES ?? 'any';
$status   = $session->status;

function pfm_step_url(int $step): string {
    $slugs = [
        1 => 'welcome', 2 => 'organization', 3 => 'main-contact', 4 => 'buyers',
        5 => 'documents', 6 => 'review', 7 => 'payment', 8 => 'confirmation',
    ];
    return '/renewal_v2/public/steps/' . $step . '-' . ($slugs[$step] ?? 'welcome') . '.php';
}

if ($requires === 'draft' && $status !== RenewalSession::STATUS_DRAFT) {
    if (in_array($status, [RenewalSession::STATUS_SUBMITTED, RenewalSession::STATUS_AWAITING_PAYMENT], true)) {
        header('Location: ' . pfm_step_url(7));
        exit;
    }
    if (in_array($status, [RenewalSession::STATUS_AWAITING_REVIEW, RenewalSession::STATUS_COMPLETED], true)) {
        header('Location: ' . pfm_step_url(8));
        exit;
    }
    header('Location: /renewal_v2/public/index.php');
    exit;
}

if ($requires === 'submitted' && !in_array($status, [
    RenewalSession::STATUS_SUBMITTED,
    RenewalSession::STATUS_AWAITING_PAYMENT,
], true)) {
    // If already paid → confirmation; if still draft → review
    if (in_array($status, [RenewalSession::STATUS_AWAITING_REVIEW, RenewalSession::STATUS_COMPLETED], true)) {
        header('Location: ' . pfm_step_url(8));
        exit;
    }
    header('Location: ' . pfm_step_url(6));
    exit;
}

if ($requires === 'paid' && !$session->isPaid()) {
    // Customer hit confirmation directly without paying yet
    header('Location: ' . pfm_step_url(7));
    exit;
}

// ── Load client row for prefill ─────────────────────────────────────
$client = Db::one(
    'SELECT client_id, co_name, business_type, business_license, pricing_level_id,
            mailing_address, city, state, zip_code, phone_number
       FROM clients WHERE client_id = ?',
    [$session->clientId]
);

if ($client === null) {
    // Shouldn't happen — session validated above — but guard anyway
    header('Location: /renewal_v2/public/index.php');
    exit;
}

// ── Defaults for header / progress-bar ─────────────────────────────
$PFM_STEP        = $PFM_STEP        ?? 1;
$PFM_STEP_TITLE  = $PFM_STEP_TITLE  ?? 'Renewal';
$PFM_PAGE_TITLE  = $PFM_STEP_TITLE . ' — Portland Flower Market Membership Renewal';
