<?php
/**
 * Shared bootstrap for every wizard step page (1-welcome.php … 8-confirmation.php).
 *
 * Provides:
 *   - Session start + token resolution + RenewalSession loading
 *   - $session  (RenewalSession)
 *   - $client   (clients row, for prefill)
 *   - Variables expected by header.php / progress-bar.php
 *
 * Behaviour:
 *   - No token / invalid token  → redirect to index.php (which shows error page)
 *   - Wrong state for this step → redirect to whichever step is appropriate
 *
 * Each step page must define BEFORE including this file:
 *     $PFM_STEP        = 1..8;           // current step number
 *     $PFM_STEP_TITLE  = 'Welcome';      // page <title> + card heading
 *     $PFM_REQUIRES    = 'draft';        // 'draft' | 'submitted' | 'paid' | 'any'
 */

declare(strict_types=1);

define('RNW_ROOT', dirname(__DIR__, 2));

require_once RNW_ROOT . '/config/config.php';
require_once RNW_ROOT . '/lib/RenewalSession.php';
require_once RNW_ROOT . '/lib/BuyerManager.php';
require_once RNW_ROOT . '/lib/DocumentUpload.php';
require_once RNW_ROOT . '/lib/StripeClient.php';

// ── Session setup (must match index.php / api_bootstrap.php) ────────
$pfmSessionDir = RNW_ROOT . '/storage/sessions';
if (is_dir($pfmSessionDir)) {
    session_save_path($pfmSessionDir);
}
if (session_status() === PHP_SESSION_NONE) {
    session_set_cookie_params([
        'lifetime' => 0,
        'path'     => '/renewal_v2/',
        'secure'   => isset($_SERVER['HTTPS']),
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_start();
}

// ── Token resolution ────────────────────────────────────────────────
// URL token wins over session token. This is the security defence
// against cross-session leak: if the URL says "load customer A", we
// load A even if the PHP session cookie was holding a stale "customer
// B" token from earlier (different browser sharing cookies, link
// pasted across browsers, etc.). If the URL token differs from the
// session token, we drop the session so the new session is clean.
$urlToken     = (string) ($_GET['token'] ?? '');
$sessionToken = (string) ($_SESSION['renewal_token'] ?? '');

if ($urlToken !== '' && $urlToken !== $sessionToken) {
    // Different customer in the URL — wipe stale session state.
    unset($_SESSION['renewal_token']);
    $sessionToken = '';
}

$token = $urlToken !== '' ? $urlToken : $sessionToken;
if ($token === '') {
    header('Location: /renewal_v2/public/index.php');
    exit;
}

$session = RenewalSession::loadOrCreate($token);
if ($session === null) {
    unset($_SESSION['renewal_token']);
    header('Location: /renewal_v2/public/index.php');
    exit;
}
$_SESSION['renewal_token'] = $session->token;

// ── CSRF token (generated by api_bootstrap on first use — ensure it exists) ─
if (empty($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}

// ── State gating ────────────────────────────────────────────────────
$requires = $PFM_REQUIRES ?? 'any';
$status   = $session->status;

/**
 * Build the URL for a wizard step, always including the current renewal
 * token as a query parameter so URLs are self-contained — the token
 * stays in the address bar across all 8 steps, copy/paste between
 * browsers works, and bookmarking the wizard mid-flow works as long
 * as the token is still inside its 30-day expiry window.
 *
 * Optional $extra lets callers attach additional query params (e.g.
 * 8-confirmation.php's session_id from Stripe, retry counter, etc.)
 * without having to know whether the URL already has a "?" or not.
 *
 * Returns just the path slug if no token is in scope (defensive
 * fallback — should never trigger because step_bootstrap loads $session
 * before this function is callable from any step page).
 */
function pfm_step_url(int $step, array $extra = []): string {
    global $session;

    $slugs = [
        1 => 'welcome', 2 => 'organization', 3 => 'main-contact', 4 => 'buyers',
        5 => 'documents', 6 => 'review', 7 => 'payment', 8 => 'confirmation',
    ];
    $path = '/renewal_v2/public/steps/' . $step . '-' . ($slugs[$step] ?? 'welcome') . '.php';

    $params = [];
    if (isset($session) && $session instanceof RenewalSession && $session->token !== '') {
        $params['token'] = $session->token;
    }
    foreach ($extra as $k => $v) {
        if ($v !== null && $v !== '') {
            $params[$k] = $v;
        }
    }

    return empty($params) ? $path : ($path . '?' . http_build_query($params));
}

if ($requires === 'draft' && $status !== RenewalSession::STATUS_DRAFT) {
    if (in_array($status, [RenewalSession::STATUS_SUBMITTED, RenewalSession::STATUS_AWAITING_PAYMENT], true)) {
        header('Location: ' . pfm_step_url(7));
        exit;
    }
    if (in_array($status, [RenewalSession::STATUS_AWAITING_REVIEW, RenewalSession::STATUS_COMPLETED], true)) {
        header('Location: ' . pfm_step_url(8));
        exit;
    }
    header('Location: /renewal_v2/public/index.php');
    exit;
}

if ($requires === 'submitted' && !in_array($status, [
    RenewalSession::STATUS_SUBMITTED,
    RenewalSession::STATUS_AWAITING_PAYMENT,
], true)) {
    // If already paid → confirmation; if still draft → review
    if (in_array($status, [RenewalSession::STATUS_AWAITING_REVIEW, RenewalSession::STATUS_COMPLETED], true)) {
        header('Location: ' . pfm_step_url(8));
        exit;
    }
    header('Location: ' . pfm_step_url(6));
    exit;
}

if ($requires === 'paid' && !$session->isPaid()) {
    // Customer hit confirmation directly without paying yet
    header('Location: ' . pfm_step_url(7));
    exit;
}

// ── Load client row for prefill ─────────────────────────────────────
$client = Db::one(
    'SELECT client_id, co_name, business_type, business_license, pricing_level_id,
            mailing_address, city, state, zip_code, phone_number
       FROM clients WHERE client_id = ?',
    [$session->clientId]
);

if ($client === null) {
    // Shouldn't happen — session validated above — but guard anyway
    header('Location: /renewal_v2/public/index.php');
    exit;
}

// ── Staff-side setup validation (early friendly error) ──────────────
// If PFM staff added a member but forgot to set the Membership Level
// dropdown in the admin form, pricing_level_id stays at 0 / NULL. The
// customer would then go through 6 forms and hit a raw technical error
// at Step 7 ("Client X has no pricing_level_id set"). Catch it HERE on
// step 1 with a friendly call-PFM message instead, so staff can fix
// the record and the customer can retry without losing draft data.
//
// Only fires while the customer is still in draft — after they've
// submitted, the wizard's payment flow won't be re-triggered, so
// there's no benefit to blocking later steps.
if (($PFM_STEP ?? 1) === 1
    && $session->status === RenewalSession::STATUS_DRAFT
    && (empty($client['pricing_level_id']) || (int) $client['pricing_level_id'] === 0)) {
    pfm_show_setup_incomplete_error($client, $session, 'membership_level');
    // function exits
}

/**
 * Render a friendly "we're not quite ready" page when staff have left
 * a mandatory field blank on the customer's client record. Includes the
 * company name, member ID, and PFM contact info so the customer can call
 * and staff can find + fix the record fast.
 *
 * @param  array            $client    clients row (must have co_name, client_id)
 * @param  RenewalSession   $session   for reference number + token preservation on retry
 * @param  string           $field     which field is missing — drives the body wording
 */
function pfm_show_setup_incomplete_error(array $client, RenewalSession $session, string $field): void
{
    http_response_code(400);

    $companyName = htmlspecialchars((string) ($client['co_name'] ?? 'Customer'), ENT_QUOTES, 'UTF-8');
    $memberId    = (int) ($client['client_id'] ?? 0);
    $reference   = htmlspecialchars($session->getReferenceNumber(), ENT_QUOTES, 'UTF-8');

    // Field-specific wording. Easy to extend if other staff-set fields
    // cause similar early errors later.
    $whatStaffMustFix = [
        'membership_level' => 'Set the "Membership Level" dropdown on the member\'s record.',
    ][$field] ?? 'Complete the member\'s record.';

    error_log(sprintf(
        '[renewal_v2] Setup-incomplete error shown for client %d (%s): missing %s',
        $memberId, (string) ($client['co_name'] ?? ''), $field
    ));

    ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>One moment please — Portland Flower Market Renewal</title>
    <link rel="icon" href="/renewal_v2/public/assets/img/pfm_logo_small.png" type="image/png">
    <link rel="stylesheet" href="/renewal_v2/public/assets/css/wizard.css">
    <style>
        .pfm-staff-note {
            background: #fff9e6;
            border-left: 4px solid #ffbc00;
            padding: 14px 18px;
            margin-top: 24px;
            font-size: 0.88rem;
            color: #6c757d;
        }
        .pfm-staff-note strong { color: #313a46; }
    </style>
</head>
<body>
<div class="pfm-shell">
    <header class="pfm-header" role="banner">
        <div class="pfm-container">
            <img src="/renewal_v2/public/assets/img/pfm_logo_small.png"
                 alt="Portland Flower Market"
                 class="pfm-header__logo">
            <div>
                <h1 class="pfm-header__title">Portland Flower Market</h1>
                <div class="pfm-header__subtitle">Annual Membership Renewal</div>
            </div>
        </div>
    </header>
    <main class="pfm-main" role="main">
        <div class="pfm-container">
            <div class="pfm-card" style="max-width: 640px; margin: 24px auto;">
                <h2 class="pfm-card__title pfm-mt-0">We&rsquo;re not quite ready for your renewal yet</h2>
                <p class="pfm-text-muted pfm-mt-0">
                    Hi <?= $companyName ?>, thank you for starting your Portland Flower
                    Market Buyer&rsquo;s Pass renewal. Before you can continue, our
                    team needs to finish setting up a small detail on your membership
                    record.
                </p>

                <div class="pfm-alert pfm-alert--info pfm-mt-2">
                    <strong>Please give us a quick call so we can sort this out:</strong>
                    <p class="pfm-mt-0" style="margin-bottom: 0;">
                        <strong>&#9742; 503-289-1500</strong><br>
                        <strong>&#9993;</strong>
                        <a href="mailto:info@ofgaflowers.com">info@ofgaflowers.com</a>
                    </p>
                </div>

                <p style="margin-top: 20px;">
                    When you call or email, please mention your <strong>Membership
                    Number</strong> so we can find your record right away:
                </p>

                <div style="background: #fafbfe; border: 1px solid #eef2f7; border-radius: 6px; padding: 14px 18px; font-family: monospace; font-size: 1.05rem; text-align: center;">
                    <strong><?= (int) $memberId ?></strong>
                </div>

                <p class="pfm-text-muted" style="margin-top: 20px; font-size: 0.92rem;">
                    Once our team has updated your record, please refresh this page
                    using the link in your renewal email and your application will
                    continue right where you left off &mdash; no information will
                    be lost.
                </p>

                <div class="pfm-staff-note">
                    <strong>For PFM staff (internal note):</strong>
                    <?= $whatStaffMustFix ?>
                    Reference: <code>client_id <?= (int) $memberId ?></code>
                    &middot; renewal <code><?= $reference ?></code>.
                </div>
            </div>
        </div>
    </main>
    <footer class="pfm-footer" role="contentinfo">
        <div class="pfm-container">
            <small class="pfm-text-muted">
                &copy; <?= date('Y') ?> Portland Flower Market
            </small>
        </div>
    </footer>
</div>
</body>
</html>
    <?php
    exit;
}

// ── Defaults for header / progress-bar ─────────────────────────────
$PFM_STEP        = $PFM_STEP        ?? 1;
$PFM_STEP_TITLE  = $PFM_STEP_TITLE  ?? 'Renewal';
$PFM_PAGE_TITLE  = $PFM_STEP_TITLE . ' — Portland Flower Market Membership Renewal';
